### PR TITLE
Small bug fixes & better compilation location

### PR DESCRIPTION
**Pull request by ShadiestGoat**
Basically, I noticed that when selecting something & pressing [, it deselects it. 
I then noticed that this plugin implements it's own auto closing braces. This is not only not needed, but is discouraged, in case obsidian decides to change something about this behaviour, or maybe the user has another plugin that tries to handle this for special effects, etc. 

Besides, obsidian already does this on it's own haha

### CODE REVIEW

**Comment by ShadiestGoat** [comment]
Ah also, why are there extra obsidian types here? just use the npm package?

**Comment by joeyuping** [comment]
Thank you so much @ShadiestGoat for the huge assistance!

- regarding types, thankyou, indeed using the npm packages would be much more straight forward.
- extra checks for math is indeed necessary, thanks
- auto closing has its uses though. If type "(", "[", or "{", within the math symbols $$, will notice that the brackets will not auto close. But typing those brackets within already closed brackets will then trigger the automatic bracket closing implemented by obsidian. Therefore, the auto closing feature included in this plugin is only to fill in that gap, so that the auto closing would happen all the time, instead of only some times. The feature can be switched off in the setting if not needed.
- The "enclose selection with brackets" feature is now implemented by obsidian itself, so I removed the codes on that. 

all in all, thank you!

**Comment by ShadiestGoat** [comment]
> auto closing has its uses though. If type "(", "[", or "{", within the math symbols $$, will notice that the brackets will not auto close. But typing those brackets within already closed brackets will then trigger the automatic bracket closing implemented by obsidian. Therefore, the auto closing feature included in this plugin is only to fill in that gap, so that the auto closing would happen all the time, instead of only some times. The feature can be switched off in the setting if not needed.

No, don't get me wrong, I see why auto closing is extremly important, I just don't think that this plugin is the thing that sound implement it. 
Currently, in almost all situations autoclosing of the brackets works, unless there is a non whitespace character after it, which is annoying. I have made [an issue on the forum](https://forum.obsidian.md/t/autoclosing-of-braces-does-not-work-if-there-is-a-character-after-it/30196)

**Comment by joeyuping** [comment]
ah I see! indeed. thank you!

for now, I thought I will just keep the function and let the user decide whether to use it or not :)

**Pull request merged**
